In [96]:
import pandas as pd

### 📁 Dataset Column Descriptions

- **`folder`**: Indicates the **original image name** (e.g., the full ID card image).
- **`filename`**: Represents the **cropped ID component** (e.g., `Id`, `First Name`, `Last Name`, `Address1`, `Address2`).
- **`text`**: Contains the **ground truth value** (i.e., the correct text content) for the corresponding cropped image.

In [113]:
df=pd.read_excel('accuracy.xlsx')
df.head()

,folder,filename,text,extracted_text_with_preproccessing,preprocessing_result,extracted_text_not_preproccessed,not_preprocessed_result,different_ocr_result
0,1,Add1.jpg,ملاحية حسن سليم,ملاجا حمن سلبم,0,بلاجة حنن مليم,0,0
1,1,Add2.jpg,مركز بيا - بنى سويف,مرغز بيا - بنى سربف,0,مرغز باء بنى سربف,0,0
2,1,FN.jpg,على,على,1,عنى,0,1
3,1,Id.jpg,28611012202932,28611012202932,1,28612012202932,0,1
4,1,LN.jpg,جمال احمد على,بىل احىد طى,0,رجنل احىد غلى,0,0

### Evaluation Criteria

- **`preprocessing_result`** and **`not_preprocessed_result`**:
  - A value of **`1`** indicates that the extracted data is **correct**.
  - A value of **`0`** indicates that the extracted data is **incorrect**.

- **`different_ocr_result`**:
  - A value of **`1`** means there is a **difference** between the OCR outputs with and without preprocessing.
  - A value of **`0`** means the outputs from both methods **match**.

In [174]:
#############################################
### Extracted Data with image preprocessing
#############################################

In [167]:
preprocessed_df=df.loc[df['preprocessing_result'] == 1]

In [168]:
preprocessed_accuracy=preprocessed_df.groupby('filename').count().sort_values(by='folder',ascending=False)['folder']
preprocessed_accuracy

filename
Id.jpg      38
FN.jpg      22
LN.jpg      16
Add2.jpg    11
Add1.jpg    10
Name: folder, dtype: int64

In [ ]:
#############################################
#### Extracted Data without image preprocessing
#############################################

In [169]:
not_preprocessed_df=df.loc[df['not_preprocessed_result'] == 1]

In [172]:
# Count the correct extracted values grouped by the Extracted Component
not_processed_accuracy=not_preprocessed_df.groupby('filename').count().sort_values(by='folder',ascending=False)['folder']
not_processed_accuracy

filename
Id.jpg      38
FN.jpg      31
LN.jpg      20
Add2.jpg    16
Add1.jpg    15
Name: folder, dtype: int64

In [171]:
# Convert the two accuracy series to one DataFrame
accuracy=pd.concat([preprocessed_accuracy,not_processed_accuracy],axis=1)
accuracy.columns=['preprocessed','not_preprocessed']
accuracy

          preprocessed  not_preprocessed
filename
Id.jpg              38                38
FN.jpg              22                31
LN.jpg              16                20
Add2.jpg            11                16
Add1.jpg            10                15

### 🔍 Observation

The **non-preprocessed images** produced **better results** compared to the **preprocessed ones**.  
This suggests that the current preprocessing techniques tend to **degrade most images**, offering improvements in only a **few specific cases**.

In [188]:
# Get the number of scanned images
images_number=len(df.loc[df['filename']=='Id.jpg'])
images_number

53

In [189]:
#############################################
#### Calculate accuracy for not preprocessed images
#############################################

In [187]:
for filename, row in accuracy.iterrows():
    name = filename.split('.')[0]
    acc = (row['not_preprocessed'] / images_number) * 100
    print(f"{name} accuracy is {acc.round(2)}%")

Id accuracy is 71.7%
FN accuracy is 58.49%
LN accuracy is 37.74%
Add2 accuracy is 30.19%
Add1 accuracy is 28.3%

⚠️ **Note:**  
The overall low accuracies are mainly attributed to the **poor quality** of the image dataset.  

✅ **Highlight:**  
Despite this, the **ID number recognition** reached an accuracy of **71%**, which is a **notable and promising result**.